// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDINKcqyJw8e9xXtRO9UAqjYgAtn8Fa7F8',
    appId: '1:56246923444:web:e4389ae7c020c8a27327e1',
    messagingSenderId: '56246923444',
    projectId: 'smarthouseapp-3f851',
    authDomain: 'smarthouseapp-3f851.firebaseapp.com',
    storageBucket: 'smarthouseapp-3f851.appspot.com',
    measurementId: 'G-NT7VZS873G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDE7I7JMHwJIg07Yu0Rj-dYwUPfxA9nhE8',
    appId: '1:56246923444:android:dc9fb42ce70c6fa87327e1',
    messagingSenderId: '56246923444',
    projectId: 'smarthouseapp-3f851',
    storageBucket: 'smarthouseapp-3f851.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHwbbZOINqG0NUW7_O-77Nm4iMQpA_lhE',
    appId: '1:56246923444:ios:457becf53e1ebc937327e1',
    messagingSenderId: '56246923444',
    projectId: 'smarthouseapp-3f851',
    storageBucket: 'smarthouseapp-3f851.appspot.com',
    iosBundleId: 'com.example.untitled1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHwbbZOINqG0NUW7_O-77Nm4iMQpA_lhE',
    appId: '1:56246923444:ios:457becf53e1ebc937327e1',
    messagingSenderId: '56246923444',
    projectId: 'smarthouseapp-3f851',
    storageBucket: 'smarthouseapp-3f851.appspot.com',
    iosBundleId: 'com.example.untitled1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDINKcqyJw8e9xXtRO9UAqjYgAtn8Fa7F8',
    appId: '1:56246923444:web:ac51a0a868a3d1f37327e1',
    messagingSenderId: '56246923444',
    projectId: 'smarthouseapp-3f851',
    authDomain: 'smarthouseapp-3f851.firebaseapp.com',
    storageBucket: 'smarthouseapp-3f851.appspot.com',
    measurementId: 'G-BDW2WTP71K',
  );
}
